language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

env:
  - SYMFONY_VERSION="3.0.*" DEPENDENCIES=dev COMPOSER_FLAGS="--prefer-stable"

before_install:
  - composer self-update

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - ./vendor/bin/simple-phpunit